- worship Him. He loves you and everyone on this Earth. He died for you. He changes life. He makes you happier. all i ask is for you to worship our LORD, Savior, and our King, Jesus Christ.
- if you're reading this, i hope you have a blessed day, and that you can get better if you're sick, become a better person if you're not too good of one. whatever needs to change for you, i hope it does.
- amen.


